# Generated by Django 4.1.7 on 2023-04-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=3)),
                ('address', models.CharField(max_length=100)),
                ('contactnumber', models.CharField(max_length=13)),
                ('date', models.DateField()),
                ('filename', models.ImageField(upload_to='images')),
                ('imgclassify', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
            ],
        ),
    ]
