# Generated by Django 4.1 on 2023-05-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biomedicalcare", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Describe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Benign", models.CharField(max_length=500)),
                ("Malignant", models.CharField(max_length=500)),
                ("Normal", models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name="patient", name="age", field=models.IntegerField(),
        ),
    ]
